-- 코드를 입력하세요
SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD a inner JOIN USED_GOODS_REPLY b ON a.BOARD_ID = b.BOARD_ID
WHERE a.CREATED_DATE BETWEEN '20221001' AND '20221031'
ORDER BY CREATED_DATE , a.TITLE