-- 코드를 작성해주세요
WITH FISH AS (
SELECT B.FISH_TYPE, B.FISH_NAME, MAX(A.LENGTH) LENGTH
FROM FISH_INFO A NATURAL JOIN FISH_NAME_INFO B
GROUP BY B.FISH_NAME, B.FISH_TYPE
) 
SELECT I.ID, F.FISH_NAME, F.LENGTH
FROM FISH F LEFT JOIN FISH_INFO I ON F.LENGTH = I.LENGTH  AND F.FISH_TYPE = I.FISH_TYPE
ORDER BY 1